//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.33440
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckMapp.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckMapp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque a convallis nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec vitae justo enim. Vivamus id semper lacus. Duis aliquam diam volutpat, consectetur erat ac, fermentum ex. Donec tincidunt venenatis placerat. Duis dignissim, arcu ut ultrices consequat, ligula ligula venenatis ipsum, id sollicitudin arcu enim ultricies tellus. Quisque placerat gravida mauris, in ultrices tellus efficitur quis. Pe [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add picture.
        /// </summary>
        public static string AddPicture {
            get {
                return ResourceManager.GetString("AddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add p.o. interest.
        /// </summary>
        public static string AddPOI {
            get {
                return ResourceManager.GetString("AddPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New trip.
        /// </summary>
        public static string AddTrip {
            get {
                return ResourceManager.GetString("AddTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trip Arrival.
        /// </summary>
        public static string AddTripArrival {
            get {
                return ResourceManager.GetString("AddTripArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schedule Date.
        /// </summary>
        public static string AddTripDate {
            get {
                return ResourceManager.GetString("AddTripDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trip Departure.
        /// </summary>
        public static string AddTripDeparture {
            get {
                return ResourceManager.GetString("AddTripDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trip Name.
        /// </summary>
        public static string AddTripName {
            get {
                return ResourceManager.GetString("AddTripName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à checkmapp.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto sync the data.
        /// </summary>
        public static string AutoSync {
            get {
                return ResourceManager.GetString("AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à choose picture.
        /// </summary>
        public static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear the history.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this note?.
        /// </summary>
        public static string ConfirmationDeleteNote {
            get {
                return ResourceManager.GetString("ConfirmationDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete theses notes?.
        /// </summary>
        public static string ConfirmationDeleteNotes {
            get {
                return ResourceManager.GetString("ConfirmationDeleteNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this photo?.
        /// </summary>
        public static string ConfirmationDeletePicture {
            get {
                return ResourceManager.GetString("ConfirmationDeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete these photos?.
        /// </summary>
        public static string ConfirmationDeletePictures {
            get {
                return ResourceManager.GetString("ConfirmationDeletePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this trip?.
        /// </summary>
        public static string ConfirmationDeleteTrip {
            get {
                return ResourceManager.GetString("ConfirmationDeleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this point of interest?.
        /// </summary>
        public static string ConfirmDeletePOI {
            get {
                return ResourceManager.GetString("ConfirmDeletePOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete theses point of interests?.
        /// </summary>
        public static string ConfirmDeletePOIs {
            get {
                return ResourceManager.GetString("ConfirmDeletePOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Trip.
        /// </summary>
        public static string ConfirmNewTrip {
            get {
                return ResourceManager.GetString("ConfirmNewTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue Trip.
        /// </summary>
        public static string ContinueTrip {
            get {
                return ResourceManager.GetString("ContinueTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes : {0}.
        /// </summary>
        public static string CountNotes {
            get {
                return ResourceManager.GetString("CountNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photos : {0}.
        /// </summary>
        public static string CountPhotos {
            get {
                return ResourceManager.GetString("CountPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à P.o. Interest : {0}.
        /// </summary>
        public static string CountPOI {
            get {
                return ResourceManager.GetString("CountPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à current trip.
        /// </summary>
        public static string CurrentTrip {
            get {
                return ResourceManager.GetString("CurrentTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date :.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day :.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No POI selected.
        /// </summary>
        public static string DefaultPoi {
            get {
                return ResourceManager.GetString("DefaultPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à city, (state, province, disctrict), country.
        /// </summary>
        public static string DepDest {
            get {
                return ResourceManager.GetString("DepDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit picture.
        /// </summary>
        public static string EditPicture {
            get {
                return ResourceManager.GetString("EditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à edit p.o. interest.
        /// </summary>
        public static string EditPoi {
            get {
                return ResourceManager.GetString("EditPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit trip.
        /// </summary>
        public static string EditTrip {
            get {
                return ResourceManager.GetString("EditTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to specify a departure and a destination.
        /// </summary>
        public static string Error_EmptyCoordinates {
            get {
                return ResourceManager.GetString("Error_EmptyCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to specify a description.
        /// </summary>
        public static string Error_EmptyDescription {
            get {
                return ResourceManager.GetString("Error_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to specify a message.
        /// </summary>
        public static string Error_EmptyMessage {
            get {
                return ResourceManager.GetString("Error_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to specify a name.
        /// </summary>
        public static string Error_EmptyName {
            get {
                return ResourceManager.GetString("Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to choose a picture.
        /// </summary>
        public static string Error_EmptyPicture {
            get {
                return ResourceManager.GetString("Error_EmptyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following errors occured :.
        /// </summary>
        public static string ErrorsDetected {
            get {
                return ResourceManager.GetString("ErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eiffel Tower.
        /// </summary>
        public static string ExamplePointInterest {
            get {
                return ResourceManager.GetString("ExamplePointInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish the trip.
        /// </summary>
        public static string FinishTrip {
            get {
                return ResourceManager.GetString("FinishTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dashboard.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your internet connection is offline. To access map features you need internet connection or download map with your cellphone..
        /// </summary>
        public static string InternetConnection {
            get {
                return ResourceManager.GetString("InternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No result found for : {0}.
        /// </summary>
        public static string InvalideSearch {
            get {
                return ResourceManager.GetString("InvalideSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à last activites.
        /// </summary>
        public static string LastActivities {
            get {
                return ResourceManager.GetString("LastActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Seven Days.
        /// </summary>
        public static string LastSevenDays {
            get {
                return ResourceManager.GetString("LastSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Six Months.
        /// </summary>
        public static string LastSixMonths {
            get {
                return ResourceManager.GetString("LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Two Weeks.
        /// </summary>
        public static string LastTwoWeeks {
            get {
                return ResourceManager.GetString("LastTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à list.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a location :.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message :.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à my notes.
        /// </summary>
        public static string MyNotes {
            get {
                return ResourceManager.GetString("MyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à my photos.
        /// </summary>
        public static string MyPhoto {
            get {
                return ResourceManager.GetString("MyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à point of interests.
        /// </summary>
        public static string MyPoi {
            get {
                return ResourceManager.GetString("MyPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internet connection missing.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Content.
        /// </summary>
        public static string NoteContent {
            get {
                return ResourceManager.GetString("NoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string NoteDate {
            get {
                return ResourceManager.GetString("NoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point of Interest.
        /// </summary>
        public static string NoteInterestPoint {
            get {
                return ResourceManager.GetString("NoteInterestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes ({0}).
        /// </summary>
        public static string NoteTripTitle {
            get {
                return ResourceManager.GetString("NoteTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à older trips.
        /// </summary>
        public static string OldTrip {
            get {
                return ResourceManager.GetString("OldTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photos ({0}).
        /// </summary>
        public static string PhotoTripTitle {
            get {
                return ResourceManager.GetString("PhotoTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Place.
        /// </summary>
        public static string PlacePOI {
            get {
                return ResourceManager.GetString("PlacePOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Points of Interest.
        /// </summary>
        public static string POITitle {
            get {
                return ResourceManager.GetString("POITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Points of interest ({0}).
        /// </summary>
        public static string POITripTitle {
            get {
                return ResourceManager.GetString("POITripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recommend this application.
        /// </summary>
        public static string RecommendApp {
            get {
                return ResourceManager.GetString("RecommendApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fr-FR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exemple de valeur de propriété d&apos;exécution.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à see notes....
        /// </summary>
        public static string SeeNotes {
            get {
                return ResourceManager.GetString("SeeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à see photos....
        /// </summary>
        public static string SeePhotos {
            get {
                return ResourceManager.GetString("SeePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a country : .
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a date : .
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à share on....
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort by Country.
        /// </summary>
        public static string SortByCountry {
            get {
                return ResourceManager.GetString("SortByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort by Date.
        /// </summary>
        public static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort Mode.
        /// </summary>
        public static string SortMode {
            get {
                return ResourceManager.GetString("SortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version number.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Wifi only.
        /// </summary>
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your journal.
        /// </summary>
        public static string YourJournal {
            get {
                return ResourceManager.GetString("YourJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your map.
        /// </summary>
        public static string YourMap {
            get {
                return ResourceManager.GetString("YourMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your timeline.
        /// </summary>
        public static string YourTimeLine {
            get {
                return ResourceManager.GetString("YourTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your travels.
        /// </summary>
        public static string YourTravels {
            get {
                return ResourceManager.GetString("YourTravels", resourceCulture);
            }
        }
    }
}
