//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckMapp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckMapp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmapp is an application to keep an history of all your trips around the world. So you can keep the best memories and share them with our friends.
        ///
        ///John-William Forcier
        ///Félix Baril
        ///Alexandre Roy.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture.
        /// </summary>
        public static string AddPicture {
            get {
                return ResourceManager.GetString("AddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add p.o. interest.
        /// </summary>
        public static string AddPOI {
            get {
                return ResourceManager.GetString("AddPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New trip.
        /// </summary>
        public static string AddTrip {
            get {
                return ResourceManager.GetString("AddTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Arrival.
        /// </summary>
        public static string AddTripArrival {
            get {
                return ResourceManager.GetString("AddTripArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Date.
        /// </summary>
        public static string AddTripDate {
            get {
                return ResourceManager.GetString("AddTripDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Departure.
        /// </summary>
        public static string AddTripDeparture {
            get {
                return ResourceManager.GetString("AddTripDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Name.
        /// </summary>
        public static string AddTripName {
            get {
                return ResourceManager.GetString("AddTripName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this trip in your calendar?.
        /// </summary>
        public static string AppCalendar {
            get {
                return ResourceManager.GetString("AppCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkmapp.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto sync the data.
        /// </summary>
        public static string AutoSync {
            get {
                return ResourceManager.GetString("AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose picture.
        /// </summary>
        public static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the history.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this note?.
        /// </summary>
        public static string ConfirmationDeleteNote {
            get {
                return ResourceManager.GetString("ConfirmationDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete theses notes?.
        /// </summary>
        public static string ConfirmationDeleteNotes {
            get {
                return ResourceManager.GetString("ConfirmationDeleteNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this photo?.
        /// </summary>
        public static string ConfirmationDeletePicture {
            get {
                return ResourceManager.GetString("ConfirmationDeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these photos?.
        /// </summary>
        public static string ConfirmationDeletePictures {
            get {
                return ResourceManager.GetString("ConfirmationDeletePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this trip?.
        /// </summary>
        public static string ConfirmationDeleteTrip {
            get {
                return ResourceManager.GetString("ConfirmationDeleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to import these data? (This will replace your current data).
        /// </summary>
        public static string ConfirmationImport {
            get {
                return ResourceManager.GetString("ConfirmationImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this point of interest? (The notes and pictures with this point of interest will also be deleted).
        /// </summary>
        public static string ConfirmDeletePOI {
            get {
                return ResourceManager.GetString("ConfirmDeletePOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete theses point of interests? (The notes and pictures with these points of interest will also be deleted).
        /// </summary>
        public static string ConfirmDeletePOIs {
            get {
                return ResourceManager.GetString("ConfirmDeletePOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to finish this trip? (You will not be able to edit it in the future).
        /// </summary>
        public static string ConfirmFinishTrip {
            get {
                return ResourceManager.GetString("ConfirmFinishTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Trip.
        /// </summary>
        public static string ConfirmNewTrip {
            get {
                return ResourceManager.GetString("ConfirmNewTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Trip.
        /// </summary>
        public static string ContinueTrip {
            get {
                return ResourceManager.GetString("ContinueTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes : {0}.
        /// </summary>
        public static string CountNotes {
            get {
                return ResourceManager.GetString("CountNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos : {0}.
        /// </summary>
        public static string CountPhotos {
            get {
                return ResourceManager.GetString("CountPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.o. Interest : {0}.
        /// </summary>
        public static string CountPOI {
            get {
                return ResourceManager.GetString("CountPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current trip.
        /// </summary>
        public static string CurrentTrip {
            get {
                return ResourceManager.GetString("CurrentTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day :.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmapp.sdf.
        /// </summary>
        public static string DBFileName {
            get {
                return ResourceManager.GetString("DBFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No POI selected.
        /// </summary>
        public static string DefaultPoi {
            get {
                return ResourceManager.GetString("DefaultPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete objects too.
        /// </summary>
        public static string DeletePOIObject {
            get {
                return ResourceManager.GetString("DeletePOIObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city, (state, province, disctrict), country.
        /// </summary>
        public static string DepDest {
            get {
                return ResourceManager.GetString("DepDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit picture.
        /// </summary>
        public static string EditPicture {
            get {
                return ResourceManager.GetString("EditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit p.o. interest.
        /// </summary>
        public static string EditPoi {
            get {
                return ResourceManager.GetString("EditPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit trip.
        /// </summary>
        public static string EditTrip {
            get {
                return ResourceManager.GetString("EditTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a departure and a destination.
        /// </summary>
        public static string Error_EmptyCoordinates {
            get {
                return ResourceManager.GetString("Error_EmptyCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a description.
        /// </summary>
        public static string Error_EmptyDescription {
            get {
                return ResourceManager.GetString("Error_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a message.
        /// </summary>
        public static string Error_EmptyMessage {
            get {
                return ResourceManager.GetString("Error_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify a name.
        /// </summary>
        public static string Error_EmptyName {
            get {
                return ResourceManager.GetString("Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a picture.
        /// </summary>
        public static string Error_EmptyPicture {
            get {
                return ResourceManager.GetString("Error_EmptyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occured :.
        /// </summary>
        public static string ErrorsDetected {
            get {
                return ResourceManager.GetString("ErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eiffel Tower.
        /// </summary>
        public static string ExamplePointInterest {
            get {
                return ResourceManager.GetString("ExamplePointInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export in progress....
        /// </summary>
        public static string ExportLoading {
            get {
                return ResourceManager.GetString("ExportLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid file has been found in folder Checkmapp in your OneDrive..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the trip.
        /// </summary>
        public static string FinishTrip {
            get {
                return ResourceManager.GetString("FinishTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting there....
        /// </summary>
        public static string GetToPOI {
            get {
                return ResourceManager.GetString("GetToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am at : {0}.
        /// </summary>
        public static string IamHere {
            get {
                return ResourceManager.GetString("IamHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import in progress....
        /// </summary>
        public static string ImportLoading {
            get {
                return ResourceManager.GetString("ImportLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet connection is offline. To access map features you need internet connection or download map with your cellphone..
        /// </summary>
        public static string InternetConnectionMap {
            get {
                return ResourceManager.GetString("InternetConnectionMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet connection is offline. .
        /// </summary>
        public static string InternetConnectionSettings {
            get {
                return ResourceManager.GetString("InternetConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found for : {0}.
        /// </summary>
        public static string InvalideSearch {
            get {
                return ResourceManager.GetString("InvalideSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to restart the application to change the language..
        /// </summary>
        public static string LangRestartApp {
            get {
                return ResourceManager.GetString("LangRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last activites.
        /// </summary>
        public static string LastActivities {
            get {
                return ResourceManager.GetString("LastActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seven Days.
        /// </summary>
        public static string LastSevenDays {
            get {
                return ResourceManager.GetString("LastSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Six Months.
        /// </summary>
        public static string LastSixMonths {
            get {
                return ResourceManager.GetString("LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Two Weeks.
        /// </summary>
        public static string LastTwoWeeks {
            get {
                return ResourceManager.GetString("LastTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a location :.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is disable in your phone settings..
        /// </summary>
        public static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message :.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument.
        /// </summary>
        public static string Monument {
            get {
                return ResourceManager.GetString("Monument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string Musee {
            get {
                return ResourceManager.GetString("Musee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my notes.
        /// </summary>
        public static string MyNotes {
            get {
                return ResourceManager.GetString("MyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my photos.
        /// </summary>
        public static string MyPhoto {
            get {
                return ResourceManager.GetString("MyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point of interests.
        /// </summary>
        public static string MyPoi {
            get {
                return ResourceManager.GetString("MyPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoPoi {
            get {
                return ResourceManager.GetString("NoPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection missing.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} note(s) in this trip.
        /// </summary>
        public static string NoteAllTime {
            get {
                return ResourceManager.GetString("NoteAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string NoteContent {
            get {
                return ResourceManager.GetString("NoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string NoteDate {
            get {
                return ResourceManager.GetString("NoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Interest.
        /// </summary>
        public static string NoteInterestPoint {
            get {
                return ResourceManager.GetString("NoteInterestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} note(s) today.
        /// </summary>
        public static string NoteToday {
            get {
                return ResourceManager.GetString("NoteToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes ({0}).
        /// </summary>
        public static string NoteTripTitle {
            get {
                return ResourceManager.GetString("NoteTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove association with this POI.
        /// </summary>
        public static string NullPOIObject {
            get {
                return ResourceManager.GetString("NullPOIObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to older trips.
        /// </summary>
        public static string OldTrip {
            get {
                return ResourceManager.GetString("OldTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos ({0}).
        /// </summary>
        public static string PhotoTripTitle {
            get {
                return ResourceManager.GetString("PhotoTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} picture(s) in this trip.
        /// </summary>
        public static string PictureAllTime {
            get {
                return ResourceManager.GetString("PictureAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} picture(s) today.
        /// </summary>
        public static string PictureToday {
            get {
                return ResourceManager.GetString("PictureToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add it to your point of interest?.
        /// </summary>
        public static string PlaceNearAdd {
            get {
                return ResourceManager.GetString("PlaceNearAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating your phone....
        /// </summary>
        public static string PlaceNearLocatePhone {
            get {
                return ResourceManager.GetString("PlaceNearLocatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.geonames.org/findNearbyWikipediaJSON?.
        /// </summary>
        public static string PlaceNearURI {
            get {
                return ResourceManager.GetString("PlaceNearURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkmapp.
        /// </summary>
        public static string PlaceNearUsername {
            get {
                return ResourceManager.GetString("PlaceNearUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places near you.
        /// </summary>
        public static string PlaceNearYou {
            get {
                return ResourceManager.GetString("PlaceNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string PlacePOI {
            get {
                return ResourceManager.GetString("PlacePOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do with the objects (notes, pictures) related to the point of interest?.
        /// </summary>
        public static string POIObject {
            get {
                return ResourceManager.GetString("POIObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of Interest.
        /// </summary>
        public static string POITitle {
            get {
                return ResourceManager.GetString("POITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of interest ({0}).
        /// </summary>
        public static string POITripTitle {
            get {
                return ResourceManager.GetString("POITripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-FR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to restart the application.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemple de valeur de propriété d&apos;exécution.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see notes....
        /// </summary>
        public static string SeeNotes {
            get {
                return ResourceManager.GetString("SeeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see photos....
        /// </summary>
        public static string SeePhotos {
            get {
                return ResourceManager.GetString("SeePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country : .
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date : .
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the end date.
        /// </summary>
        public static string SetEndDate {
            get {
                return ResourceManager.GetString("SetEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share on....
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Country.
        /// </summary>
        public static string SortByCountry {
            get {
                return ResourceManager.GetString("SortByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Date.
        /// </summary>
        public static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Mode.
        /// </summary>
        public static string SortMode {
            get {
                return ResourceManager.GetString("SortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Friends.
        /// </summary>
        public static string TravelFriends {
            get {
                return ResourceManager.GetString("TravelFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date : {0}.
        /// </summary>
        public static string TripBeginDate {
            get {
                return ResourceManager.GetString("TripBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date : {0}.
        /// </summary>
        public static string TripEndDate {
            get {
                return ResourceManager.GetString("TripEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the start date and must be lower or equal than the current date..
        /// </summary>
        public static string ValidatorEndDate {
            get {
                return ResourceManager.GetString("ValidatorEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our website.
        /// </summary>
        public static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Wifi only.
        /// </summary>
        public static string WifiOnly {
            get {
                return ResourceManager.GetString("WifiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your journal.
        /// </summary>
        public static string YourJournal {
            get {
                return ResourceManager.GetString("YourJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your map.
        /// </summary>
        public static string YourMap {
            get {
                return ResourceManager.GetString("YourMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your position.
        /// </summary>
        public static string YourPosition {
            get {
                return ResourceManager.GetString("YourPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your timeline.
        /// </summary>
        public static string YourTimeLine {
            get {
                return ResourceManager.GetString("YourTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your travels.
        /// </summary>
        public static string YourTravels {
            get {
                return ResourceManager.GetString("YourTravels", resourceCulture);
            }
        }
    }
}
